### Testing 404 error route
GET http://localhost:1996/route/that/doesNotExists

### Testing storer login route
POST http://localhost:1996/api/storer/login
Content-Type: application/json

{
  "args": {
    "email": "acecom.soporte@gmail.com",
    "password": "anthony&bryan"
  }
}

### Testing producer signUp route
POST http://localhost:1996/api/producer/signUp
Content-Type: application/json

{
  "args": {
    "email": "holi6@boli.com",
    "password": "holi",
    "country": "Peru",
    "name": "ACECOM"
  }
}

### Testing producer signIn route
POST http://localhost:1996/api/producer/login
Content-Type: application/json

{
  "args": {
    "email": "holi6@boli.com",
    "password": "holi"
  }
}

### Testing add product route
POST http://localhost:1996/api/product/addProductWithoutImage
Content-Type: application/json

{
  "args": {
    "description": "This is a test",
    "name": "Test 11",
    "price": 19.99,
    "producer": "60e345d7861ccec771415378",
    "stock": 2
  }
}

### Testing remove product route
DELETE http://localhost:1996/api/product/removeProduct/60e4d89c3e1233448af85f02

### Testing update stock route
PATCH http://localhost:1996/api/product/updateStock
Content-Type: application/json

{
  "args": {
    "id": "60e4ce962ba9e809c0479aa4",
    "stock": -1
  }
}

### Testing list products
GET http://localhost:1996/api/product/list/60e345d7861ccec771415378

### Testing create warehouse
POST http://localhost:1996/api/warehouse/addWarehouse
Content-Type: application/json

{
  "args": {
    "name": "Warehouse 3",
    "country": "Peru",
    "address": "Av. Las Violetas 1196",
    "owner": "60e27730aeacd357571d940d"
  }
}

### Testing delete warehouse
DELETE http://localhost:1996/api/warehouse/removeWarehouse/60e587dfb2fb2ae4cc227e0a