### Testing 404 error route
GET http://localhost:1996/route/that/doesNotExists

### Testing storer login route
POST http://localhost:1996/api/storer/login
Content-Type: application/json

{
  "args": {
    "email": "acecom.soporte@gmail.com",
    "password": "anthony&bryan"
  }
}

### Testing producer signUp route
POST http://localhost:1996/api/producer/signUp
Content-Type: application/json

{
  "args": {
    "email": "holi6@boli.com",
    "password": "holi",
    "country": "Peru",
    "name": "ACECOM"
  }
}

### Testing producer signIn route
POST http://localhost:1996/api/producer/login
Content-Type: application/json

{
  "args": {
    "email": "holi6@boli.com",
    "password": "holi"
  }
}

### Testing add product route
POST http://localhost:1996/api/product/addProductWithoutImage
Content-Type: application/json

{
  "args": {
    "description": "This is a test",
    "name": "Test 8",
    "price": 19.99,
    "producer": "60e345d7861ccec771415378",
    "stock": 2
  }
}